Buger/member
practiceSpringWithSixProject/member pull request #5
Opened 2023-05-11 14:18 UTC by juxnn

피드 스펙 업로드

2023-05-12 09:59 UTC, heozeop requested changes
스펙은 충분히 상세해주신 것 같습니다! 
메인에 있는 파일만 지워주세요!
@juxnn

2023-05-12 09:59 UTC, heozeop commented on FEED.md
> +- 신고 및 차단 기능.
[요청] 사용하지 않는 파일 지우기
이 파일은 지워주세요!!

2023-05-12 09:59 UTC, heozeop commented on specification/FeedSpec.md
> +    - 12주의 기간 내에서 구현 가능한 기능을 선정하는 것에 중점을 둡니다.
이 프로젝트는 2주안에 끝나는 토이입니당! ㅎㅎ
차후 세부 기능 정해지고 다른 그룹에 레포 팔거에요!! ㅎㅎ

2023-05-13 02:29 UTC, juxnn commented on specification/FeedSpec.md
> +    - 12주의 기간 내에서 구현 가능한 기능을 선정하는 것에 중점을 둡니다.
넵! 이해했습니다.

2023-05-13 03:41 UTC, heozeop approved these changes

2023-05-13 20:38 UTC, merged