initial commit: spring boot project
practiceSpringWithSixProject/member pull request #6
Opened 2023-05-11 20:03 UTC by SoonWookHwang

스프링 부트 프로젝트 기초 세팅

2023-05-12 09:54 UTC, heozeop requested changes
빠른 작업 감사합니다!
설정에 lint도 .idea도 추가해 주시면 좋을 것 같아요!

2023-05-12 09:54 UTC, heozeop commented on .gitignore
> +
[질문] 추가하신 파일들의 용도
추가하신 두개 파일의 역할과 추가하신 이유가 궁금합니다!

2023-05-12 09:54 UTC, heozeop commented on .idea/aws.xml
> +</project>
[요청] eof는 개행 부탁드립니다.
나중에 린트 추가되면 해결될 문제 같아요!

2023-05-12 09:54 UTC, heozeop commented on build.gradle
> +	runtimeOnly 'com.mysql:mysql-connector-j'
[요청] postgresql 로 바꿔주세요!
우리는 postgresql 쓸예정이에요!

2023-05-16 08:35 UTC, SoonWookHwang commented on .gitignore
> +
추후에 스프링 시큐리티에 사용될 시크릿키를 해당 파일에 작성해서 보안관리를 하기 때문에 ignore처리를 하였습니다

2023-05-16 11:50 UTC, heozeop approved these changes
LGTM

2023-05-16 11:51 UTC, merged